### ISSUE TITLE
[EPIC] app 0.3.0 milestone

### ISSUE THREAD

**Issue by pmnxis** [pmnxis/billmock-app-rs#35]
### Goal
- [x] OTP for mass-production and Serial-Number for display on ARM-DAP or card-terminal (#33)
- [x] `DisplayHwInfo` impl and activate when release from `DisplayRom` state (#36)
- [x] `0.5 mini` version hardware support and show `DisplayRom` on LCD when new tactile switch clicked. ( #38 )
- [x] MPtool and dummy elf header for mass production ( #40 )
- [x] Fix incorrect uptime field by starving event. Instead re-write EEPROM page periodically ( #43 )
- [x] Enhance business logic ( #45 )

### Postponed goal
- ~~`PushSaleSlotInfoPartialInhibit` impl and retouch sale slot inhibition by `INH` signal or `DIP_SWITCH`.~~

**Comment by pmnxis** [comment]
`PushSaleSlotInfoPartialInhibit impl and retouch sale slot inhibition by INH signal or DIP_SWITCH.`
is postponed to 0.4.0 milestone because of KICC module has bug on related feature.
