### ISSUE TITLE
[EPIC] app 0.3.1 milestone

### ISSUE THREAD

**Issue by pmnxis** [pmnxis/billmock-app-rs#47]
### Goal
- [x] Factory Reset EEPROM (coin/credit count only  and  whole area) by SVC button (0.5 series hardware only) ( #49 )
- [x] Indicate NDA crate is enabled in MP tool, and MP fingerprint ( #48 )
- [x] Indicate card terminal version and warn to display ( #51 )
- [x] Up to date document ( https://github.com/pmnxis/billmock-app-rs/commit/06fb086de637753fdcd549b8e8a41ac4bc96230f )
